// This file will be auto-generated by tauri-specta when the app runs in debug mode.
// Manual placeholder for development until first app launch.

import { invoke } from "@tauri-apps/api/core";

export type AgentInfo = {
  id: string;
  filename: string;
  name: string;
  description: string | null;
  color: string | null;
  model: string | null;
  tools: string[] | null;
  enabled: boolean;
  path: string;
  section: string;
  group: string;
  invalid_config: boolean;
};

export async function getAgents(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_agents");
}

export async function getSkills(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_skills");
}

export async function getCommands(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_commands");
}

export async function toggleItem(
  path: string,
  enable: boolean,
  section: string,
): Promise<AgentInfo> {
  return await invoke<AgentInfo>("toggle_item", { path, enable, section });
}

export async function frontendReady(): Promise<void> {
  return await invoke<void>("frontend_ready");
}
