// This file will be auto-generated by tauri-specta when the app runs in debug mode.
// Manual placeholder for development until first app launch.

import { invoke } from "@tauri-apps/api/core";

export type AgentInfo = {
  id: string;
  filename: string;
  name: string;
  description: string | null;
  color: string | null;
  model: string | null;
  tools: string[] | null;
  enabled: boolean;
  path: string;
  section: string;
  group: string;
  scope: string;
  invalid_config: boolean;
};

export type SetupEntry = {
  id: string;
  enabled: boolean;
};

export type Setup = {
  name: string;
  created_at: string;
  entries: SetupEntry[];
};

export async function getAgents(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_agents");
}

export async function getSkills(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_skills");
}

export async function getCommands(): Promise<AgentInfo[]> {
  return await invoke<AgentInfo[]>("get_commands");
}

export async function toggleItem(
  path: string,
  enable: boolean,
  section: string,
): Promise<AgentInfo> {
  return await invoke<AgentInfo>("toggle_item", { path, enable, section });
}

export type ToggleBatchItem = {
  path: string;
  enable: boolean;
};

export async function toggleBatch(
  items: ToggleBatchItem[],
): Promise<string[]> {
  return await invoke<string[]>("toggle_batch", { items });
}

export async function frontendReady(): Promise<void> {
  return await invoke<void>("frontend_ready");
}

export async function getSetups(): Promise<Setup[]> {
  return await invoke<Setup[]>("get_setups");
}

export async function getActiveSetup(): Promise<string | null> {
  return await invoke<string | null>("get_active_setup");
}

export async function clearActiveSetup(): Promise<void> {
  return await invoke<void>("clear_active_setup");
}

export async function createSetup(name: string): Promise<Setup> {
  return await invoke<Setup>("create_setup", { name });
}

export async function deleteSetup(name: string): Promise<void> {
  return await invoke<void>("delete_setup", { name });
}

export async function applySetup(name: string): Promise<string[]> {
  return await invoke<string[]>("apply_setup", { name });
}

export async function exportSetup(name: string): Promise<string> {
  return await invoke<string>("export_setup", { name });
}

export async function importSetup(json: string): Promise<Setup> {
  return await invoke<Setup>("import_setup", { json });
}
